kind: pipeline
type: docker
name: default


volumes:
- name: docker-certs
  host:
    path: /etc/docker/certs.d/

steps:

# A generic step (commands executed inside a container)
- name: greeting
  image: busybox:1.32
  when:
    event:
    - push
    - tag
  environment:
    DB_USER: admin
    DB_PASS:
      from_secret: db_password
    REGISTRY_PASSWORD:
      from_secret: registry_password
  commands:
  - echo Hello World
  - ls -hal
  - pwd
  # https://docs.drone.io/pipeline/environment/reference/
  #- env
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}
  # https://discourse.drone.io/t/problems-with-secrets/3286
  - ./echo-secrets.sh


# A step that builds the Docker image
# see https://docs.drone.io/plugins/popular/docker/
- name: docker-build
  image: plugins/docker
  when:
    event:
    - push
    - tag
  # Todo
  #environment:
  #  REGISTRY_ADDRESS:
  #    from_secret: registry_address
  #volumes:
  #- name: docker-certs
  #  path: /etc/docker/certs.d/
  #environment:
  #  PASSWORD:
  #    from_secret: registry_password
  settings:
    debug: true
    username: user
    password:
      from_secret: registry_password
    # Fixme 
    custom_dns: 10.0.12.60
    #insecure: true
    registry: registry-dev-1-opertusmundi:30474
    repo: registry-dev-1-opertusmundi:30474/hello-octapus
    tags:
    - '1.7'
    #- ${DRONE_TAG}
    build_args:
    - VERSION=1.7
    #- VERSION=${DRONE_TAG}
