---
kind: pipeline
type: docker
name: prepare-1

steps:

- name: step-1
  image: busybox:1.32
  when:
    event:
    - push
    - tag
  environment:
    Foo: Bar
  commands:
  - echo "Hello World" > hello.txt
  - ls -hal .
  - pwd
  - env


---
kind: pipeline
type: docker
name: default

#
# Steps
#

steps:

# A generic step (commands executed inside a container)
- name: maven-build
  image: maven:3.8.6-eclipse-temurin-17-alpine
  when:
    event:
    - push
    - tag
  environment:
    {}
  commands:
  - mvn -B package


