---
kind: pipeline
type: docker
name: prepare-1

trigger:
 ref: 
 - 'refs/tags/1.[0-9].0-x'
 - 'refs/tags/1.[1-9][0-9].0-x'

steps:

- name: step-1
  image: busybox:1.32
  when:
    event:
    - push
  environment:
    Foo: Bar
  commands:
  - echo "Hello World" > hello.txt
  - ls -hal .
  - pwd
  - env


---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    exclude:
    - 'refs/tags/1.[0-9].0-x'
    - 'refs/tags/1.[1-9][0-9].0-x'   

steps:

- name: maven-build
  image: maven:3.6.3-openjdk-8 
  when:
    event:
    - push
    - tag
  environment:
    {}
  commands:
  - mvn -B package shade:shade

- name: exec-jar
  image: openjdk:8-jre-alpine 
  when:
    event:
    - push
    - tag
  environment:
    {}
  commands:
  - java -jar target/hello-octapus-*.jar

- name: publish-image-1
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    debug: true
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: alexakis/hello-octapus
    tags:
    - ${DRONE_TAG}
    mirror: http://registry-mirror:5000
    build_args:
    - VERSION=${DRONE_TAG}

