---
kind: pipeline
type: docker
name: prepare-1

trigger:
 ref: 
 - 'refs/tags/*-prepare'

steps:

- name: step-1
  image: busybox:1.32
  when:
    event:
    - push
    - tag
  environment:
    Foo: Bar
  commands:
  - echo "Hello World" > hello.txt
  - ls -hal .
  - pwd
  - env

- name: publish-image
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    dockerfile: base.dockerfile
    context: .
    debug: true
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: alexakis/hello-octapus-base
    tags:
    - "${DRONE_SEMVER_SHORT}"
    - "${DRONE_SEMVER_MAJOR}:${DRONE_SEMVER_MINOR}"
    mirror: http://registry-mirror:5000

---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    exclude:
    - 'refs/tags/*-prepare'

steps:

- name: maven-build
  image: maven:3.6.3-openjdk-8 
  when:
    event:
    - push
    - tag
  environment:
    {}
  commands:
  - mvn -B package shade:shade

- name: exec-jar
  image: openjdk:8-jre-alpine 
  when:
    event:
    - push
    - tag
  environment:
    {}
  commands:
  - java -jar target/hello-octapus-*.jar

- name: publish-image
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    debug: true
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: alexakis/hello-octapus
    tags:
    - ${DRONE_TAG}
    mirror: http://registry-mirror:5000
    build_args:
    - VERSION=${DRONE_TAG}

