kind: pipeline
type: docker
name: default


steps:

# A generic step (commands executed inside a container)
- name: greeting
  image: busybox:1.32
  when:
    event:
    - push
    - tag
  environment:
    DB_USER: admin
    DB_PASS:
      from_secret: db_password
    REGISTRY_PASSWORD:
      from_secret: registry_password
  commands:
  - echo Hello World
  - ls -hal .
  - ls -R -hal /etc/docker/certs.d
  - pwd
  # https://docs.drone.io/pipeline/environment/reference/
  - env
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}
  # https://discourse.drone.io/t/problems-with-secrets/3286
  - ./echo-secrets.sh


# A step that builds the Docker image (see https://docs.drone.io/plugins/popular/docker/)
- name: docker-build
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    #debug: true
    username: user
    password:
      from_secret: registry_password
    #custom_dns: ${NAMESERVER_1}
    #registry: registry-dev-1-opertusmundi:30474
    registry: ${REGISTRY_HOST}:${REGISTRY_PORT}
    #repo: registry-dev-1-opertusmundi:30474/hello-octapus
    repo: ${REGISTRY_HOST}:${REGISTRY_PORT}/hello-octapus
    tags:
    - '1'
    - ${DRONE_TAG}
    build_args:
    - VERSION=${DRONE_TAG}
