kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: busybox:1.32
  environment:
    DB_USER: admin
    DB_PASS:
      from_secret: db-password
  commands:
  - echo Hello World
  - ls -hal
  - pwd
  # https://docs.drone.io/pipeline/environment/reference/
  #- env
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}
  # https://discourse.drone.io/t/problems-with-secrets/3286
  - ./echo-secrets.sh

 
trigger:
  event:
  - push
  - tag

