kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: busybox:1.32
  commands:
  - echo Hello World
  - ls -hal
  - pwd
  - git branch -va
  - git log --oneline 
 
trigger:
  event:
  #- push
  - tag

