kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: busybox:1.32
  environment:
    db_user: admin
    db_pass:
      from_secret: db-password
  commands:
  - echo Hello World
  - ls -hal
  - pwd
  # https://docs.drone.io/pipeline/environment/reference/
  - env
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}

 
trigger:
  event:
  - push
  - tag

