language: python
python:
  - "2.7"

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE USER tester PASSWORD 'tester'" -U postgres
  - psql -c "CREATE DATABASE hello_octapus OWNER tester" -U postgres
  - psql -c "CREATE EXTENSION postgis" -U postgres hello_octapus
  - psql -c "CREATE TABLE octapus(id integer, friendly_name varchar(80))" -U tester hello_octapus

# command to install dependencies
install:
  - pip install -r requirements.txt


# command to run tests
script:
  - python test-1.py
  - bash test-2.sh
  - psql -c "SELECT user" -U tester hello_octapus
  - psql -c '\d' -U tester hello_octapus
