language: java

jdk:
- 'openjdk8'

env:
  global:
   - ARTIFACT_VERSION=1.0-SNAPSHOT
  matrix:
   - FOO=foo1 BAZ=baz1

cache:
  directories:
  - "$HOME/.m2"

sudo: required

services:
- postgresql
- docker

addons:
  postgresql: '9.5'
  apt:
    packages:
    - postgresql-9.5-postgis-2.3

install:

- sudo apt-get install -y ruby ruby-dev
- sudo gem install sass --version "=3.4.24"

- docker pull openjdk:8-jdk

- mvn dependency:resolve

before_script:
- psql -c "CREATE USER tester PASSWORD 'tester'" -U postgres
- psql -c "CREATE DATABASE hello_octapus OWNER tester" -U postgres
- psql -c "CREATE EXTENSION postgis" -U postgres hello_octapus
- psql -f scripts/db/init.sql -U tester hello_octapus

script:
- set -e
- bash env-dump.sh
- (cd resources && ls -hal)

- mvn verify
- mvn install shade:shade
- ./run-example.sh 

- psql -h localhost -c "SELECT user" -U tester hello_octapus
- psql -h localhost -c '\d' -U tester hello_octapus
- psql -h localhost -c 'SELECT * FROM octapus' -U tester hello_octapus

- ./build-docker-image.sh
- ./run-example-container.sh

