language: java

jdk:
- 'openjdk8'

env:
  global:
  matrix:
   - FOO=foo1 BAZ=baz1

cache:
  directories:
  - "$HOME/.m2"

services:
- postgresql

addons:
  postgresql: '9.5'
  apt:
    packages:
    - postgresql-9.5-postgis-2.3

before_script:
- psql -c "CREATE USER tester PASSWORD 'tester'" -U postgres
- psql -c "CREATE DATABASE hello_octapus OWNER tester" -U postgres
- psql -c "CREATE EXTENSION postgis" -U postgres hello_octapus
- psql -f scripts/db/init.sql -U tester hello_octapus

install:
- mvn install

script:
- bash env-dump.sh
- mvn verify
- java -jar target/hello-octapus-1.0-SNAPSHOT.jar
- psql -c "SELECT user" -U tester hello_octapus
- psql -c '\d' -U tester hello_octapus
- psql -c 'SELECT * FROM octapus' -U tester hello_octapus

