language: python
python:
- '2.7'
env:
  global:
    # an example of a secret environment variable: SECRET_THING
    # use something like: cat secrets/env-file | travis encrypt --add
    secure: nyVheJ329dSUeNuGc7HDvjw2AV/HSh5bXIZuP33RR1b9lgfcLIE2puZzBJQ1hB2J1jUKGIwXEhJaS/KJZRWsJ+f2VvSM61ho4l0EVov/ZEA5dTAjRRqy35+eLJYd8lEMuijVjeoM3spelQiC4oB+8x1gskelplLD2c+8hiMjT8TEaGC2vfrMbcV9WZ74/g58LeC9Hhkvr7X6Z9SlVsPJkOgkwqtCx20Tnimji/MXoo0qp6Y0MXiWDEBwlANrpXkjkP1msfP3FZk8xFc0dZ2/FUiXSlGKa+N1j7vSmmUB55aJ5yrnMKNllbdQtvIPgt4T2FaD5b6QK1Y9WzeUeykIELlKXngK8Qw1xRpN/zfUTweuImr/jKubG8Nf0+a1fVMevoI3d75ZuoUrw6xUYtaUcJoEK8X5ZM4sWYMntcF1q+TuBAqvQWFUEUIjHhKspXkz/5Xonsm3SPRXeMONIg3e5EJ8m5iy6oe+y1mg1NDwMNK0FLXNz0NMZiomrQNwj554PJdmf+wizKuSSE2fjAD1Hlt6orYOJCdEkO/vHQjvd0AuKtLvr3ZnwVEZmdHMdv9jsWI/ppSwH6Mosi+0jdWMtUZBYleiATCmtotUWvcp3gRp662EY54S2u4HhZx0JpJYJnRVzuCpzS+0JysG3abV5j+Br4sBEPuQPK3im+d2jeQ=
  matrix:
   - FOO=foo1 BAZ=baz1
   - FOO=foo2 BAZ=baz2 QUX=qux2
services:
- postgresql
addons:
  postgresql: '9.5'
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
before_script:
- psql -c "CREATE USER tester PASSWORD 'tester'" -U postgres
- psql -c "CREATE DATABASE hello_octapus OWNER tester" -U postgres
- psql -c "CREATE EXTENSION postgis" -U postgres hello_octapus
- psql -f scripts/db/init.sql -U tester hello_octapus
install:
- pip install -r requirements.txt
script:
- python test-1.py
- bash env-dump.sh
- psql -c "SELECT user" -U tester hello_octapus
- psql -c '\d' -U tester hello_octapus
- psql -c 'SELECT * FROM octapus' -U tester hello_octapus
