language: python
python:
  - "2.7"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER tester PASSWORD 'tester'" -U postgres
  - psql -c "CREATE DATABASE hello_octapus OWNER tester" -U postgres

# command to install dependencies
install:
  - pip install -r requirements.txt


# command to run tests
script:
  - python test-1.py
  - bash test-2.sh
  - psql -c "SELECT now()" -U tester hello_octapus
