apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-data
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-1-dynamic
  volumeMode: Filesystem

