namespace: default

helm:
  releaseName: 'redis-c1'
  
  chart: "redis"
  repo: "https://charts.bitnami.com/bitnami"
  version: "12.1.2"
  
  valuesFiles:
  - values-local.yml
  values:
    master:
      podLabels:
        updatedAt: >-
          20220107T00:44:00
    slave:
      podLabels:
        updatedAt: >- 
          20220107T00:44:00

