namespace: default

# https://fleet.rancher.io/0.9/ref-fleet-yaml#reference
helm:
  releaseName: 'redis-1'
  
  chart: "redis"
  repo: "https://charts.bitnami.com/bitnami"
  version: "12.1.2"
  
  # values from repo files
  valuesFiles:
  - values-local.yml
  
  # inline values
  values:
    master:
      podLabels:
        updatedAt: '20220107'
    slave:
      podLabels:
        updatedAt: '20220107'

  # values from cluster resources
  valuesFrom:
  - secretKeyRef:
      # a secret with the `auth.password` value
      name: redis-1-auth
      namespace: default
      key: values.yaml
