namespace: default

# https://fleet.rancher.io/0.9/ref-fleet-yaml#reference
helm:
  releaseName: 'helloworld'
  
  values:
    # override part of chart's values

    service:
      type: ClusterIP
    
    # examples on how to use cluster's (clusters.fleet.cattle.io resource in Rancher)

    key1:
      cluster-name: "${ .ClusterName }"
    key2:
      labelsAsJson: "${ .ClusterLabels | toJson | quote }"
      annotationsAsJson: "${ .ClusterAnnotations | toJson | quote }"
