namespace: argocd

configMapGenerator:
- name: target-env
  literals:
  - REPO_URL=https://github.com/drmalex07/hello-octapus
  - REVISION=af96daf

resources:
- storage/app.yaml
- compute-pi/app.yaml
- echo-pi/app.yaml


# Apply a uniform source for {repoURL,targetRevision} for applications
replacements:

- source:
   kind: ConfigMap
   name: target-env
   fieldPath: data.REPO_URL
  targets:
  - select:
      group: argoproj.io 
      kind: Application
    fieldPaths:
    - 'spec.sources.*.repoURL'

- source:
   kind: ConfigMap
   name: target-env
   fieldPath: data.REVISION
  targets:
  - select:
      group: argoproj.io 
      kind: Application
    fieldPaths:
    - 'spec.sources.*.targetRevision'
