name: hello service containers
run-name: Hello service containers

on: 
  push:
    branches:
    - 'example'
    - 'github-workflows-example'

jobs:
   
   helloworld:
    runs-on: ubuntu-20.04
    container:
      image: postgres:10.14-alpine
    env:
      PGHOST: postgres-1
      PGUSER: postgres
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: ls -hal .
    - run: pwd
    - run: uname -a
    - run: mkdir secrets
    - run: >-
        dd if=/dev/urandom count=6 bs=1 status=none | base64 | tr -d '\n' > secrets/tester1-password
    - run: pg_isready -t5
    - run: ping -c3 postgres-1.
    - run: >-
        echo "\set password '$(cat secrets/tester1-password)'" > .psqlrc-create-test1-database
    - run: >-
        psql -f db-init-scripts/s01-create-test1-database.sql
      env:
        PSQLRC: .psqlrc-create-test1-database
    - run: psql -l
    services:
      "postgres-1":
        image: postgres:10.14-alpine
        volumes:
        - db-data:/var/lib/postgresql/data
        # cannpt do this ... see https://github.com/orgs/community/discussions/42127
        #- ./db-init-scripts:/docker-entrypoint-initdb.d/
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
