# https://docs.github.com/en/actions/using-containerized-services/about-service-containers
name: hello containers
run-name: Hello containers

on: 
  push:
    branches:
    - 'example'
    - 'github-workflows-example'

jobs:
  
  helloworld:
    runs-on: ubuntu-20.04
    container:
      image: alpine:3.15
      volumes:
      # NOTE: You dont need to mount the workspace (done automatically by workflow runner, mounted at $HOME)
      - /data-1:/data-1
    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: ls -hal .
    - run: pwd
    - run: uname -a
    - run: df -hT
    - run: ls -hal /data-1
    - run: |
        mkdir -v /data-1/echo
        echo "Hello, on $(date)" > /data-1/echo/hello.txt
    # store a part of our output (artifact) in order to be used by other jobs of same workflow
    - uses: actions/upload-artifact@v3
      with:
        name: data-1
        path: /data-1
        retention-days: 1

  hellogalaxy:
    runs-on: ubuntu-20.04
    needs:
    - helloworld
    container:
      image: debian:11.1-slim
      volumes:
      # reuse the same volume from previous job?
      # (we must use download-artifact for target path)
      - /data-1:/data-1
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: data-1
        path: /data-1
    - run: env | sort
    - run: ls -hal .
    - run: pwd
    - run: uname -a
    - run: df -hT
    - run: ls -hal -R /data-1
    - run: cat /data-1/echo/hello.txt

