name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
    - github-workflows-example
    tags:
    - '1.*'

jobs:
  
  helloworld:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - run: ls -hal
    # see variables on available contexts (https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
    - run: >-
        echo "Github Ref: ${{ github.ref }}"
    - run: env
    - run: whoami
    - run: apt-get --version
    - run: sudo apt-get install jq
    - run: uname -a
    - run: docker info
    - run: java -version 
    #- run: 'false' # if a step fails, the runner will skip next steps
    - run: mvn -version
    - run: mvn package shade:shade -B
    - run: java -jar target/hello-octapus.jar
  
  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages
  build_image:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      # assign an id to this step, to be used later
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}
    - run: >-
        echo "Tags: ${{ steps.meta.outputs.tags }}"
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
