name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
    - github-workflows-example
    tags:
    - '1.*'

jobs:
  
  helloworld:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with: # note: for private submodules we need a fine-grained access token (default token only covers top-level repo)
        submodules: 'true'
        # access token (fine-grained PAT) with (extra) read permissions on private submodules
        token: ${{ secrets.ACCESS_TOKEN }} 
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - run: ls -hal
    - run: env | sort
    - run: ls -hal scripts
    # see variables on available contexts (https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
    - run: >-
        echo "Github Ref: ${{ github.ref }}"
    - run: uname -a
    - run: whoami
    - run: apt-get --version
    - run: sudo apt-get install jq
    - run: jq --version
    - run: docker info
    - run: java -version 
    #- run: 'false' # if a step fails, the runner will skip next steps
    - run: mvn -version
    - run: mvn package shade:shade -B
    - run: java -jar target/hello-octapus.jar
  
  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages
  build_image:
    runs-on: ubuntu-20.04
    needs: # make dependent on succesfull completion of another job
    - helloworld
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      # assign an id to this step, to be used later
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}
    - run: >-
        echo "Tags: ${{ steps.meta.outputs.tags }}"
    # https://github.com/docker/build-push-action/blob/e27bcee4eb9e7b4bc168418e3364c4482120393a/docs/advanced/cache.md
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: src/main/docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # https://docs.docker.com/build/cache/backends/gha/
        # https://github.com/docker/build-push-action/blob/e27bcee4eb9e7b4bc168418e3364c4482120393a/docs/advanced/cache.md
        cache-from: type=gha
        cache-to: type=gha,mode=max
