name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

# run manually
#on: workflow_dispatch

on: 
  push:
    branches:
    - 'ci-*'
    - github-workflows-example
    tags:
    - '1.*'

jobs:
  
  helloworld:
    runs-on: ubuntu-20.04
    env:
      FOO: bar
    steps:
    - uses: actions/checkout@v3
      with: 
        # note: for private submodules we need a fine-grained access token (default token only covers top-level repo)
        # see https://github.com/orgs/community/discussions/25516
        submodules: 'true'
        # access token (fine-grained PAT) with (extra) read permissions on private submodules
        token: ${{ secrets.ACCESS_TOKEN }} 
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - run: ls -hal
    - run: env | sort
    - run: ls -hal scripts
    # see variables on available contexts (https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
    - run: >-
        echo "Github Ref: ${{ github.ref }}"
    - run: uname -a
    - run: whoami
    - run: apt-get --version
    - run: sudo apt-get install jq
    - run: jq --version
    - name: Dump github context
      # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
      run: |
        echo '${{ toJson(github) }}' | jq .
    - run: docker info
    - run: java -version 
    #- run: 'false' # if a step fails, the runner will skip next steps
    - run: mvn -version
    - run: mvn package shade:shade -B
    - run: java -jar target/hello-octapus.jar
    # an example of setting an env variable
    - run: >-
        echo "NOW=$(date)" >> $GITHUB_ENV
    - run: echo "NOW=$NOW"
    
  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages
  build_image:
    runs-on: ubuntu-20.04
    if: >-
      github.ref_type == 'tag'
    needs: # make dependent on succesfull completion of another job
    - helloworld
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      # assign an id to this step, to be used later
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}
    - run: >-
        echo "Tags: ${{ steps.meta.outputs.tags }}"
    # https://github.com/docker/build-push-action/blob/e27bcee4eb9e7b4bc168418e3364c4482120393a/docs/advanced/cache.md
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: src/main/docker/Dockerfile
        build-args: |
           git_url=${{ github.event.repository.url }}
           git_build_time=${{ github.event.head_commit.timestamp }}
           git_tags=${{ github.ref_name }}
           git_commit=${{ github.sha }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        ## or give tags explicitly ...
        #tags: |
        #  ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        #  ghcr.io/${{ github.repository }}:${{ github.ref_name }}-simple
        #  ghcr.io/${{ github.repository }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        # https://docs.docker.com/build/cache/backends/gha/
        # https://github.com/docker/build-push-action/blob/e27bcee4eb9e7b4bc168418e3364c4482120393a/docs/advanced/cache.md
        cache-from: type=gha
        cache-to: type=gha,mode=max
