name: sync-subtree-to-another-repo
#run-name: Sync a subtree of this repo to another repo 

# run manually
#on: workflow_dispatch

on: 
  push:
    paths:
    - 'resources/*'
    branches:
    - 'github-workflows-commit-to-another-repo'
    tags:
    - '1.*'

jobs:
  
  helloworld:
    runs-on: ubuntu-22.04
    env:
      FOO: bar
    steps:
    - run: git version
    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.REPO_READER_ACCESS_TOKEN }} 
    - run: ls -hal
    - run: env | sort
    - run: >-
        echo "Github Ref: ${{ github.ref }}"
    - run: uname -a
    - run: whoami
    - name: Dump github context
      run: |
        echo '${{ toJson(github) }}' | jq .
    - run: >-
        echo "NOW=$(date)" >> $GITHUB_ENV
    - run: echo "NOW=$NOW"
    
